services:
  app:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image: registry.appelevate.cz/coree:latest
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any

  db:
    image: postgres:13-alpine
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
    environment:
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

secrets:
  postgres_user:
    external: true
  postgres_password:
    external: true
  postgres_db:
    external: true
volumes:
  postgres_data: