basePath: /
definitions:
  dbexample.UserCreate:
    properties:
      age:
        type: integer
      name:
        type: string
    required:
    - age
    - name
    type: object
  dbexample.UserGet:
    properties:
      age:
        type: integer
      id:
        type: string
      name:
        type: string
    required:
    - age
    - id
    - name
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /crash:
    get:
      consumes:
      - application/json
      description: Crash the server
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Crashes the server and sends a report to Sentry
  /db-example/user:
    post:
      consumes:
      - application/json
      description: create a user using post
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dbexample.UserCreate'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/dbexample.UserGet'
      summary: Create a user
  /db-example/user/{name}:
    get:
      consumes:
      - application/json
      description: Get a User by name
      parameters:
      - description: User name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/dbexample.UserGet'
      summary: Get a User by name
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
