name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and tag the Docker image
        run: |
          IMAGE_TAG=ghcr.io/${{ github.repository_owner }}/coree:$(date +%s)
          docker build . --file Dockerfile --tag $IMAGE_TAG
          docker tag $IMAGE_TAG ghcr.io/${{ github.repository_owner }}/coree:latest

      - name: Push the Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/coree:latest
